name: Nginx Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v1.2.1
        with:
          config: ${{ secrets.KUBECONFIG }}
          args: |
            config set-context --current --namespace=my-namespace
            apply -f kubernetes/k8s-nginx-statefulset.yml